import type { City } from "./types";

export const CITIES: City[] = [
  {
    name: "Marseille",
    slug: "marseille",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13001–13016",
    localHook: "Premier port de Méditerranée, zones portuaires, entrepôts logistiques et tissu industriel des quartiers Est.",
    relatedBlogSlug: "panneaux-solaires-entreprises-paca-2025",
    neighborSlugs: ["aix-en-provence","arles","aubagne"],
    neighborNames: ["Aix-en-Provence","Arles","Aubagne"],
  },
  {
    name: "Aix-en-Provence",
    slug: "aix-en-provence",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13100",
    localHook: "Technopôle de l'Arbois, zones Activités de Rousset et bassin tertiaire.",
    relatedBlogSlug: "autoconsommation-solaire-reduire-facture-electricite",
    neighborSlugs: ["arles","aubagne","martigues"],
    neighborNames: ["Arles","Aubagne","Martigues"],
  },
  {
    name: "Arles",
    slug: "arles",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13200",
    localHook: "Parc industriel de Trigance, agroalimentaire et logistique sur l'axe Rhône-Saint-Gilles.",
    relatedBlogSlug: "installation-photovoltaique-marseille-professionnels",
    neighborSlugs: ["aubagne","martigues","istres"],
    neighborNames: ["Aubagne","Martigues","Istres"],
  },
  {
    name: "Aubagne",
    slug: "aubagne",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13400",
    localHook: "Pôle Garlaban, industries manufacturières et zones d'activités le long de l'A50.",
    relatedBlogSlug: "ombrieres-photovoltaiques-parking-entreprise",
    neighborSlugs: ["martigues","istres","salon-de-provence"],
    neighborNames: ["Martigues","Istres","Salon-de-Provence"],
  },
  {
    name: "Martigues",
    slug: "martigues",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13500",
    localHook: "Raffinerie, pétrochimie et zones industrielles de Lavéra et Croix-Sainte.",
    relatedBlogSlug: "aides-subventions-panneaux-solaires-entreprises-2025",
    neighborSlugs: ["istres","salon-de-provence","la-ciotat"],
    neighborNames: ["Istres","Salon-de-Provence","La Ciotat"],
  },
  {
    name: "Istres",
    slug: "istres",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13800",
    localHook: "Base aéronautique, industries de défense et zones d'activités de L'Estaque et Rassuen.",
    relatedBlogSlug: "installation-solaire-avignon-vaucluse",
    neighborSlugs: ["salon-de-provence","la-ciotat","vitrolles"],
    neighborNames: ["Salon-de-Provence","La Ciotat","Vitrolles"],
  },
  {
    name: "Salon-de-Provence",
    slug: "salon-de-provence",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13300",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Salon-de-Provence et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "installation-solaire-toulon-var",
    neighborSlugs: ["la-ciotat","vitrolles","fos-sur-mer"],
    neighborNames: ["La Ciotat","Vitrolles","Fos-sur-Mer"],
  },
  {
    name: "La Ciotat",
    slug: "la-ciotat",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13600",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de La Ciotat et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "panneaux-solaires-aix-en-provence",
    neighborSlugs: ["vitrolles","fos-sur-mer","miramas"],
    neighborNames: ["Vitrolles","Fos-sur-Mer","Miramas"],
  },
  {
    name: "Vitrolles",
    slug: "vitrolles",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13127",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Vitrolles et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "panneaux-solaires-entreprises-paca-2025",
    neighborSlugs: ["fos-sur-mer","miramas","gardanne"],
    neighborNames: ["Fos-sur-Mer","Miramas","Gardanne"],
  },
  {
    name: "Fos-sur-Mer",
    slug: "fos-sur-mer",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13270",
    localHook: "Grand port maritime, sidérurgie et vastes surfaces de toitures industrielles.",
    relatedBlogSlug: "autoconsommation-solaire-reduire-facture-electricite",
    neighborSlugs: ["miramas","gardanne","lambesc"],
    neighborNames: ["Miramas","Gardanne","Lambesc"],
  },
  {
    name: "Miramas",
    slug: "miramas",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13140",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Miramas et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "installation-photovoltaique-marseille-professionnels",
    neighborSlugs: ["gardanne","lambesc","trets"],
    neighborNames: ["Gardanne","Lambesc","Trets"],
  },
  {
    name: "Gardanne",
    slug: "gardanne",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13120",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Gardanne et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "ombrieres-photovoltaiques-parking-entreprise",
    neighborSlugs: ["lambesc","trets","roquevaire"],
    neighborNames: ["Lambesc","Trets","Roquevaire"],
  },
  {
    name: "Lambesc",
    slug: "lambesc",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13410",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Lambesc et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "aides-subventions-panneaux-solaires-entreprises-2025",
    neighborSlugs: ["trets","roquevaire","chateauneuf-les-martigues"],
    neighborNames: ["Trets","Roquevaire","Châteauneuf-les-Martigues"],
  },
  {
    name: "Trets",
    slug: "trets",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13530",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Trets et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "installation-solaire-avignon-vaucluse",
    neighborSlugs: ["roquevaire","chateauneuf-les-martigues","berre-l-etang"],
    neighborNames: ["Roquevaire","Châteauneuf-les-Martigues","Berre-l'Étang"],
  },
  {
    name: "Roquevaire",
    slug: "roquevaire",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13360",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Roquevaire et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "installation-solaire-toulon-var",
    neighborSlugs: ["chateauneuf-les-martigues","berre-l-etang","port-de-bouc"],
    neighborNames: ["Châteauneuf-les-Martigues","Berre-l'Étang","Port-de-Bouc"],
  },
  {
    name: "Châteauneuf-les-Martigues",
    slug: "chateauneuf-les-martigues",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13220",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Châteauneuf-les-Martigues et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "panneaux-solaires-aix-en-provence",
    neighborSlugs: ["berre-l-etang","port-de-bouc","gignac-la-nerthe"],
    neighborNames: ["Berre-l'Étang","Port-de-Bouc","Gignac-la-Nerthe"],
  },
  {
    name: "Berre-l'Étang",
    slug: "berre-l-etang",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13130",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Berre-l'Étang et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "panneaux-solaires-entreprises-paca-2025",
    neighborSlugs: ["port-de-bouc","gignac-la-nerthe","bouc-bel-air"],
    neighborNames: ["Port-de-Bouc","Gignac-la-Nerthe","Bouc-Bel-Air"],
  },
  {
    name: "Port-de-Bouc",
    slug: "port-de-bouc",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13110",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Port-de-Bouc et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "autoconsommation-solaire-reduire-facture-electricite",
    neighborSlugs: ["gignac-la-nerthe","bouc-bel-air","peynier"],
    neighborNames: ["Gignac-la-Nerthe","Bouc-Bel-Air","Peynier"],
  },
  {
    name: "Gignac-la-Nerthe",
    slug: "gignac-la-nerthe",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13180",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Gignac-la-Nerthe et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "installation-photovoltaique-marseille-professionnels",
    neighborSlugs: ["bouc-bel-air","peynier","peyrolles-en-provence"],
    neighborNames: ["Bouc-Bel-Air","Peynier","Peyrolles-en-Provence"],
  },
  {
    name: "Bouc-Bel-Air",
    slug: "bouc-bel-air",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13320",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Bouc-Bel-Air et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "ombrieres-photovoltaiques-parking-entreprise",
    neighborSlugs: ["peynier","peyrolles-en-provence","saint-cannat"],
    neighborNames: ["Peynier","Peyrolles-en-Provence","Saint-Cannat"],
  },
  {
    name: "Peynier",
    slug: "peynier",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13790",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Peynier et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "aides-subventions-panneaux-solaires-entreprises-2025",
    neighborSlugs: ["peyrolles-en-provence","saint-cannat","rognac"],
    neighborNames: ["Peyrolles-en-Provence","Saint-Cannat","Rognac"],
  },
  {
    name: "Peyrolles-en-Provence",
    slug: "peyrolles-en-provence",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13860",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Peyrolles-en-Provence et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "installation-solaire-avignon-vaucluse",
    neighborSlugs: ["saint-cannat","rognac","lancon-provence"],
    neighborNames: ["Saint-Cannat","Rognac","Lançon-Provence"],
  },
  {
    name: "Saint-Cannat",
    slug: "saint-cannat",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13760",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Saint-Cannat et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "installation-solaire-toulon-var",
    neighborSlugs: ["rognac","lancon-provence","velaux"],
    neighborNames: ["Rognac","Lançon-Provence","Velaux"],
  },
  {
    name: "Rognac",
    slug: "rognac",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13340",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Rognac et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "panneaux-solaires-aix-en-provence",
    neighborSlugs: ["lancon-provence","velaux","pennes-mirabeau"],
    neighborNames: ["Lançon-Provence","Velaux","Pennes-Mirabeau"],
  },
  {
    name: "Lançon-Provence",
    slug: "lancon-provence",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13680",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Lançon-Provence et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "panneaux-solaires-entreprises-paca-2025",
    neighborSlugs: ["velaux","pennes-mirabeau","plan-de-cuques"],
    neighborNames: ["Velaux","Pennes-Mirabeau","Plan-de-Cuques"],
  },
  {
    name: "Velaux",
    slug: "velaux",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13880",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Velaux et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "autoconsommation-solaire-reduire-facture-electricite",
    neighborSlugs: ["pennes-mirabeau","plan-de-cuques","allauch"],
    neighborNames: ["Pennes-Mirabeau","Plan-de-Cuques","Allauch"],
  },
  {
    name: "Pennes-Mirabeau",
    slug: "pennes-mirabeau",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13170",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Pennes-Mirabeau et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "installation-photovoltaique-marseille-professionnels",
    neighborSlugs: ["plan-de-cuques","allauch","cassis"],
    neighborNames: ["Plan-de-Cuques","Allauch","Cassis"],
  },
  {
    name: "Plan-de-Cuques",
    slug: "plan-de-cuques",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13380",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Plan-de-Cuques et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "ombrieres-photovoltaiques-parking-entreprise",
    neighborSlugs: ["allauch","cassis"],
    neighborNames: ["Allauch","Cassis"],
  },
  {
    name: "Allauch",
    slug: "allauch",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13190",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Allauch et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "aides-subventions-panneaux-solaires-entreprises-2025",
    neighborSlugs: ["cassis","aix-en-provence"],
    neighborNames: ["Cassis","Aix-en-Provence"],
  },
  {
    name: "Cassis",
    slug: "cassis",
    departmentCode: "13",
    departmentSlug: "bouches-du-rhone",
    departmentName: "Bouches-du-Rhône",
    postalCode: "13260",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Cassis et de son bassin d'emploi dans les Bouches-du-Rhône.",
    relatedBlogSlug: "installation-solaire-avignon-vaucluse",
    neighborSlugs: ["marseille","aix-en-provence"],
    neighborNames: ["Marseille","Aix-en-Provence"],
  },
  {
    name: "Avignon",
    slug: "avignon",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84000",
    localHook: "MIN d'Avignon, zones Agroparc et tissu agroalimentaire du Grand Avignon.",
    relatedBlogSlug: "installation-solaire-toulon-var",
    neighborSlugs: ["carpentras","orange","cavaillon"],
    neighborNames: ["Carpentras","Orange","Cavaillon"],
  },
  {
    name: "Carpentras",
    slug: "carpentras",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84200",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Carpentras et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "panneaux-solaires-aix-en-provence",
    neighborSlugs: ["orange","cavaillon","apt"],
    neighborNames: ["Orange","Cavaillon","Apt"],
  },
  {
    name: "Orange",
    slug: "orange",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84100",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Orange et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "panneaux-solaires-entreprises-paca-2025",
    neighborSlugs: ["cavaillon","apt","pertuis"],
    neighborNames: ["Cavaillon","Apt","Pertuis"],
  },
  {
    name: "Cavaillon",
    slug: "cavaillon",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84300",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Cavaillon et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "autoconsommation-solaire-reduire-facture-electricite",
    neighborSlugs: ["apt","pertuis","sorgues"],
    neighborNames: ["Apt","Pertuis","Sorgues"],
  },
  {
    name: "Apt",
    slug: "apt",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84400",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Apt et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "installation-photovoltaique-marseille-professionnels",
    neighborSlugs: ["pertuis","sorgues","vedene"],
    neighborNames: ["Pertuis","Sorgues","Vedène"],
  },
  {
    name: "Pertuis",
    slug: "pertuis",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84120",
    localHook: "Zone industrielle de Pertuis et lien économique entre Luberon et département du Var.",
    relatedBlogSlug: "ombrieres-photovoltaiques-parking-entreprise",
    neighborSlugs: ["sorgues","vedene","le-pontet"],
    neighborNames: ["Sorgues","Vedène","Le Pontet"],
  },
  {
    name: "Sorgues",
    slug: "sorgues",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84700",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Sorgues et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "aides-subventions-panneaux-solaires-entreprises-2025",
    neighborSlugs: ["vedene","le-pontet","monteux"],
    neighborNames: ["Vedène","Le Pontet","Monteux"],
  },
  {
    name: "Vedène",
    slug: "vedene",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84270",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Vedène et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "installation-solaire-avignon-vaucluse",
    neighborSlugs: ["le-pontet","monteux","courthezon"],
    neighborNames: ["Le Pontet","Monteux","Courthézon"],
  },
  {
    name: "Le Pontet",
    slug: "le-pontet",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84130",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Le Pontet et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "installation-solaire-toulon-var",
    neighborSlugs: ["monteux","courthezon","pernes-les-fontaines"],
    neighborNames: ["Monteux","Courthézon","Pernes-les-Fontaines"],
  },
  {
    name: "Monteux",
    slug: "monteux",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84170",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Monteux et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "panneaux-solaires-aix-en-provence",
    neighborSlugs: ["courthezon","pernes-les-fontaines","l-isle-sur-la-sorgue"],
    neighborNames: ["Courthézon","Pernes-les-Fontaines","L'Isle-sur-la-Sorgue"],
  },
  {
    name: "Courthézon",
    slug: "courthezon",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84350",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Courthézon et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "panneaux-solaires-entreprises-paca-2025",
    neighborSlugs: ["pernes-les-fontaines","l-isle-sur-la-sorgue","bollene"],
    neighborNames: ["Pernes-les-Fontaines","L'Isle-sur-la-Sorgue","Bollène"],
  },
  {
    name: "Pernes-les-Fontaines",
    slug: "pernes-les-fontaines",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84210",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Pernes-les-Fontaines et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "autoconsommation-solaire-reduire-facture-electricite",
    neighborSlugs: ["l-isle-sur-la-sorgue","bollene","valreas"],
    neighborNames: ["L'Isle-sur-la-Sorgue","Bollène","Valréas"],
  },
  {
    name: "L'Isle-sur-la-Sorgue",
    slug: "l-isle-sur-la-sorgue",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84800",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de L'Isle-sur-la-Sorgue et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "installation-photovoltaique-marseille-professionnels",
    neighborSlugs: ["bollene","valreas","vaison-la-romaine"],
    neighborNames: ["Bollène","Valréas","Vaison-la-Romaine"],
  },
  {
    name: "Bollène",
    slug: "bollene",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84500",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Bollène et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "ombrieres-photovoltaiques-parking-entreprise",
    neighborSlugs: ["valreas","vaison-la-romaine","gordes"],
    neighborNames: ["Valréas","Vaison-la-Romaine","Gordes"],
  },
  {
    name: "Valréas",
    slug: "valreas",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84600",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Valréas et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "aides-subventions-panneaux-solaires-entreprises-2025",
    neighborSlugs: ["vaison-la-romaine","gordes","cheval-blanc"],
    neighborNames: ["Vaison-la-Romaine","Gordes","Cheval-Blanc"],
  },
  {
    name: "Vaison-la-Romaine",
    slug: "vaison-la-romaine",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84110",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Vaison-la-Romaine et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "installation-solaire-avignon-vaucluse",
    neighborSlugs: ["gordes","cheval-blanc","cadenet"],
    neighborNames: ["Gordes","Cheval-Blanc","Cadenet"],
  },
  {
    name: "Gordes",
    slug: "gordes",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84220",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Gordes et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "installation-solaire-toulon-var",
    neighborSlugs: ["cheval-blanc","cadenet","lourmarin"],
    neighborNames: ["Cheval-Blanc","Cadenet","Lourmarin"],
  },
  {
    name: "Cheval-Blanc",
    slug: "cheval-blanc",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84460",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Cheval-Blanc et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "panneaux-solaires-aix-en-provence",
    neighborSlugs: ["cadenet","lourmarin"],
    neighborNames: ["Cadenet","Lourmarin"],
  },
  {
    name: "Cadenet",
    slug: "cadenet",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84160",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Cadenet et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "panneaux-solaires-entreprises-paca-2025",
    neighborSlugs: ["lourmarin","carpentras"],
    neighborNames: ["Lourmarin","Carpentras"],
  },
  {
    name: "Lourmarin",
    slug: "lourmarin",
    departmentCode: "84",
    departmentSlug: "vaucluse",
    departmentName: "Vaucluse",
    postalCode: "84160",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Lourmarin et de son bassin d'emploi dans les Vaucluse.",
    relatedBlogSlug: "autoconsommation-solaire-reduire-facture-electricite",
    neighborSlugs: ["avignon","carpentras"],
    neighborNames: ["Avignon","Carpentras"],
  },
  {
    name: "Toulon",
    slug: "toulon",
    departmentCode: "83",
    departmentSlug: "var",
    departmentName: "Var",
    postalCode: "83000",
    localHook: "Base navale, chantiers navals et zones industrielles de La Seyne et Ollioules.",
    relatedBlogSlug: "installation-photovoltaique-marseille-professionnels",
    neighborSlugs: ["frejus","la-seyne-sur-mer","brignoles"],
    neighborNames: ["Fréjus","La Seyne-sur-Mer","Brignoles"],
  },
  {
    name: "Fréjus",
    slug: "frejus",
    departmentCode: "83",
    departmentSlug: "var",
    departmentName: "Var",
    postalCode: "83600",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Fréjus et de son bassin d'emploi dans les Var.",
    relatedBlogSlug: "ombrieres-photovoltaiques-parking-entreprise",
    neighborSlugs: ["la-seyne-sur-mer","brignoles","draguignan"],
    neighborNames: ["La Seyne-sur-Mer","Brignoles","Draguignan"],
  },
  {
    name: "La Seyne-sur-Mer",
    slug: "la-seyne-sur-mer",
    departmentCode: "83",
    departmentSlug: "var",
    departmentName: "Var",
    postalCode: "83500",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de La Seyne-sur-Mer et de son bassin d'emploi dans les Var.",
    relatedBlogSlug: "aides-subventions-panneaux-solaires-entreprises-2025",
    neighborSlugs: ["brignoles","draguignan","hyeres"],
    neighborNames: ["Brignoles","Draguignan","Hyères"],
  },
  {
    name: "Brignoles",
    slug: "brignoles",
    departmentCode: "83",
    departmentSlug: "var",
    departmentName: "Var",
    postalCode: "83170",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Brignoles et de son bassin d'emploi dans les Var.",
    relatedBlogSlug: "installation-solaire-avignon-vaucluse",
    neighborSlugs: ["draguignan","hyeres","saint-raphael"],
    neighborNames: ["Draguignan","Hyères","Saint-Raphaël"],
  },
  {
    name: "Draguignan",
    slug: "draguignan",
    departmentCode: "83",
    departmentSlug: "var",
    departmentName: "Var",
    postalCode: "83300",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Draguignan et de son bassin d'emploi dans les Var.",
    relatedBlogSlug: "installation-solaire-toulon-var",
    neighborSlugs: ["hyeres","saint-raphael","ollioules"],
    neighborNames: ["Hyères","Saint-Raphaël","Ollioules"],
  },
  {
    name: "Hyères",
    slug: "hyeres",
    departmentCode: "83",
    departmentSlug: "var",
    departmentName: "Var",
    postalCode: "83400",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Hyères et de son bassin d'emploi dans les Var.",
    relatedBlogSlug: "panneaux-solaires-aix-en-provence",
    neighborSlugs: ["saint-raphael","ollioules","la-garde"],
    neighborNames: ["Saint-Raphaël","Ollioules","La Garde"],
  },
  {
    name: "Saint-Raphaël",
    slug: "saint-raphael",
    departmentCode: "83",
    departmentSlug: "var",
    departmentName: "Var",
    postalCode: "83700",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Saint-Raphaël et de son bassin d'emploi dans les Var.",
    relatedBlogSlug: "panneaux-solaires-entreprises-paca-2025",
    neighborSlugs: ["ollioules","la-garde","six-fours-les-plages"],
    neighborNames: ["Ollioules","La Garde","Six-Fours-les-Plages"],
  },
  {
    name: "Ollioules",
    slug: "ollioules",
    departmentCode: "83",
    departmentSlug: "var",
    departmentName: "Var",
    postalCode: "83190",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Ollioules et de son bassin d'emploi dans les Var.",
    relatedBlogSlug: "autoconsommation-solaire-reduire-facture-electricite",
    neighborSlugs: ["la-garde","six-fours-les-plages"],
    neighborNames: ["La Garde","Six-Fours-les-Plages"],
  },
  {
    name: "La Garde",
    slug: "la-garde",
    departmentCode: "83",
    departmentSlug: "var",
    departmentName: "Var",
    postalCode: "83130",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de La Garde et de son bassin d'emploi dans les Var.",
    relatedBlogSlug: "installation-photovoltaique-marseille-professionnels",
    neighborSlugs: ["six-fours-les-plages","frejus"],
    neighborNames: ["Six-Fours-les-Plages","Fréjus"],
  },
  {
    name: "Six-Fours-les-Plages",
    slug: "six-fours-les-plages",
    departmentCode: "83",
    departmentSlug: "var",
    departmentName: "Var",
    postalCode: "83140",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Six-Fours-les-Plages et de son bassin d'emploi dans les Var.",
    relatedBlogSlug: "ombrieres-photovoltaiques-parking-entreprise",
    neighborSlugs: ["toulon","frejus"],
    neighborNames: ["Toulon","Fréjus"],
  },
  {
    name: "Nice",
    slug: "nice",
    departmentCode: "06",
    departmentSlug: "alpes-maritimes",
    departmentName: "Alpes-Maritimes",
    postalCode: "06000",
    localHook: "Aéroport Nice Côte d'Azur, technopoles et zones commerciales de la métropole.",
    relatedBlogSlug: "aides-subventions-panneaux-solaires-entreprises-2025",
    neighborSlugs: ["antibes","cannes","grasse"],
    neighborNames: ["Antibes","Cannes","Grasse"],
  },
  {
    name: "Antibes",
    slug: "antibes",
    departmentCode: "06",
    departmentSlug: "alpes-maritimes",
    departmentName: "Alpes-Maritimes",
    postalCode: "06600",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Antibes et de son bassin d'emploi dans les Alpes-Maritimes.",
    relatedBlogSlug: "installation-solaire-avignon-vaucluse",
    neighborSlugs: ["cannes","grasse","menton"],
    neighborNames: ["Cannes","Grasse","Menton"],
  },
  {
    name: "Cannes",
    slug: "cannes",
    departmentCode: "06",
    departmentSlug: "alpes-maritimes",
    departmentName: "Alpes-Maritimes",
    postalCode: "06400",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Cannes et de son bassin d'emploi dans les Alpes-Maritimes.",
    relatedBlogSlug: "installation-solaire-toulon-var",
    neighborSlugs: ["grasse","menton"],
    neighborNames: ["Grasse","Menton"],
  },
  {
    name: "Grasse",
    slug: "grasse",
    departmentCode: "06",
    departmentSlug: "alpes-maritimes",
    departmentName: "Alpes-Maritimes",
    postalCode: "06130",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Grasse et de son bassin d'emploi dans les Alpes-Maritimes.",
    relatedBlogSlug: "panneaux-solaires-aix-en-provence",
    neighborSlugs: ["menton","antibes"],
    neighborNames: ["Menton","Antibes"],
  },
  {
    name: "Menton",
    slug: "menton",
    departmentCode: "06",
    departmentSlug: "alpes-maritimes",
    departmentName: "Alpes-Maritimes",
    postalCode: "06500",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Menton et de son bassin d'emploi dans les Alpes-Maritimes.",
    relatedBlogSlug: "panneaux-solaires-entreprises-paca-2025",
    neighborSlugs: ["nice","antibes"],
    neighborNames: ["Nice","Antibes"],
  },
  {
    name: "Manosque",
    slug: "manosque",
    departmentCode: "04",
    departmentSlug: "alpes-de-haute-provence",
    departmentName: "Alpes-de-Haute-Provence",
    postalCode: "04100",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Manosque et de son bassin d'emploi dans les Alpes-de-Haute-Provence.",
    relatedBlogSlug: "autoconsommation-solaire-reduire-facture-electricite",
    neighborSlugs: ["digne-les-bains","sisteron","forcalquier"],
    neighborNames: ["Digne-les-Bains","Sisteron","Forcalquier"],
  },
  {
    name: "Digne-les-Bains",
    slug: "digne-les-bains",
    departmentCode: "04",
    departmentSlug: "alpes-de-haute-provence",
    departmentName: "Alpes-de-Haute-Provence",
    postalCode: "04000",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Digne-les-Bains et de son bassin d'emploi dans les Alpes-de-Haute-Provence.",
    relatedBlogSlug: "installation-photovoltaique-marseille-professionnels",
    neighborSlugs: ["sisteron","forcalquier","volx"],
    neighborNames: ["Sisteron","Forcalquier","Volx"],
  },
  {
    name: "Sisteron",
    slug: "sisteron",
    departmentCode: "04",
    departmentSlug: "alpes-de-haute-provence",
    departmentName: "Alpes-de-Haute-Provence",
    postalCode: "04200",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Sisteron et de son bassin d'emploi dans les Alpes-de-Haute-Provence.",
    relatedBlogSlug: "ombrieres-photovoltaiques-parking-entreprise",
    neighborSlugs: ["forcalquier","volx"],
    neighborNames: ["Forcalquier","Volx"],
  },
  {
    name: "Forcalquier",
    slug: "forcalquier",
    departmentCode: "04",
    departmentSlug: "alpes-de-haute-provence",
    departmentName: "Alpes-de-Haute-Provence",
    postalCode: "04300",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Forcalquier et de son bassin d'emploi dans les Alpes-de-Haute-Provence.",
    relatedBlogSlug: "aides-subventions-panneaux-solaires-entreprises-2025",
    neighborSlugs: ["volx","digne-les-bains"],
    neighborNames: ["Volx","Digne-les-Bains"],
  },
  {
    name: "Volx",
    slug: "volx",
    departmentCode: "04",
    departmentSlug: "alpes-de-haute-provence",
    departmentName: "Alpes-de-Haute-Provence",
    postalCode: "04130",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Volx et de son bassin d'emploi dans les Alpes-de-Haute-Provence.",
    relatedBlogSlug: "installation-solaire-avignon-vaucluse",
    neighborSlugs: ["manosque","digne-les-bains"],
    neighborNames: ["Manosque","Digne-les-Bains"],
  },
  {
    name: "Gap",
    slug: "gap",
    departmentCode: "05",
    departmentSlug: "hautes-alpes",
    departmentName: "Hautes-Alpes",
    postalCode: "05000",
    localHook: "Préfecture des Hautes-Alpes, industries alpines, tourisme et équipements publics à fort potentiel solaire.",
    relatedBlogSlug: "installation-solaire-toulon-var",
    neighborSlugs: ["briancon","embrun","laragne-monteglin"],
    neighborNames: ["Briançon","Embrun","Laragne-Montéglin"],
  },
  {
    name: "Briançon",
    slug: "briancon",
    departmentCode: "05",
    departmentSlug: "hautes-alpes",
    departmentName: "Hautes-Alpes",
    postalCode: "05100",
    localHook: "Vallée de la Durance, activités touristiques et bâtiments tertiaires en altitude.",
    relatedBlogSlug: "panneaux-solaires-aix-en-provence",
    neighborSlugs: ["embrun","laragne-monteglin","veynes"],
    neighborNames: ["Embrun","Laragne-Montéglin","Veynes"],
  },
  {
    name: "Embrun",
    slug: "embrun",
    departmentCode: "05",
    departmentSlug: "hautes-alpes",
    departmentName: "Hautes-Alpes",
    postalCode: "05200",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Embrun et de son bassin d'emploi dans les Hautes-Alpes.",
    relatedBlogSlug: "panneaux-solaires-entreprises-paca-2025",
    neighborSlugs: ["laragne-monteglin","veynes"],
    neighborNames: ["Laragne-Montéglin","Veynes"],
  },
  {
    name: "Laragne-Montéglin",
    slug: "laragne-monteglin",
    departmentCode: "05",
    departmentSlug: "hautes-alpes",
    departmentName: "Hautes-Alpes",
    postalCode: "05300",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Laragne-Montéglin et de son bassin d'emploi dans les Hautes-Alpes.",
    relatedBlogSlug: "autoconsommation-solaire-reduire-facture-electricite",
    neighborSlugs: ["veynes","briancon"],
    neighborNames: ["Veynes","Briançon"],
  },
  {
    name: "Veynes",
    slug: "veynes",
    departmentCode: "05",
    departmentSlug: "hautes-alpes",
    departmentName: "Hautes-Alpes",
    postalCode: "05400",
    localHook: "Entreprises, artisans, entrepôts et bâtiments tertiaires de Veynes et de son bassin d'emploi dans les Hautes-Alpes.",
    relatedBlogSlug: "installation-photovoltaique-marseille-professionnels",
    neighborSlugs: ["gap","briancon"],
    neighborNames: ["Gap","Briançon"],
  }
];

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getCitiesByDepartment(deptSlug: string): City[] {
  return CITIES.filter((c) => c.departmentSlug === deptSlug);
}
