import type { CityPageContent } from "./types";

type CitySeed = {
  slug: string;
  name: string;
  code: string;
  department: string;
  sunshine: string;
  geography: string;
  zones: [string, string, string];
  sectors: [string, string, string, string];
  neighbors: [
    { slug: string; name: string },
    { slug: string; name: string },
    { slug: string; name: string }
  ];
  relatedBlogSlug: string;
};

function buildContent(seed: CitySeed): CityPageContent {
  const [zoneA, zoneB, zoneC] = seed.zones;
  const [sectorA, sectorB, sectorC, sectorD] = seed.sectors;
  const zoneList = `${zoneA}, ${zoneB} et ${zoneC}`;
  const sectorList = `${sectorA}, ${sectorB}, ${sectorC} et ${sectorD}`;

  return {
    title: `Panneaux Solaires ${seed.name} (${seed.code}) | Electrotech — Photovoltaïque B2B`,
    metaDescription: `Solaire pro à ${seed.name} (${seed.code}) : ${zoneA}, ${sectorA}. Installateur QualiPV RGE. Devis ☎ 04 91 87 11 08`,
    h1: `Installation panneaux solaires à ${seed.name} (${seed.code}) — Electrotech`,
    heroDescription: `Electrotech accompagne les entreprises, entrepôts et collectivités de ${seed.name} avec des installations photovoltaïques dimensionnées pour ${seed.geography}. Certification QualiPV RGE — étude gratuite au 04 91 87 11 08.`,
    sections: [
      {
        heading: `Pourquoi ${seed.name} offre un vrai potentiel solaire`,
        paragraphs: [
          `Le territoire de ${seed.name} profite d'un ensoleillement favorable, avec ${seed.sunshine}. Cette régularité permet de stabiliser la production annuelle et de sécuriser le retour sur investissement des entreprises locales. Pour chaque site B2B, nous modélisons les scénarios de consommation afin d'ajuster la puissance installée sans surdimensionner.`,
          `La lecture du site intègre la géographie réelle de ${seed.geography}. L'implantation à ${seed.name} doit tenir compte des vents dominants, des ombrages et de la structure du bâtiment. Nous réalisons une étude de productible détaillée avant toute proposition commerciale.`,
          `Les acteurs de ${sectorA} et ${sectorB} trouvent dans le photovoltaïque un levier concret de compétitivité. Electrotech QualiPV RGE accompagne ces profils avec des composants adaptés au climat local et un suivi de performance après mise en service.`,
        ],
      },
      {
        heading: `Zones economiques et profils de consommation a ${seed.name}`,
        paragraphs: [
          `L'activite locale s'articule notamment autour de ${zoneList}, trois poles qui structurent une part importante des besoins energetiques. Dans ces secteurs, les consommations sont souvent concentrees sur les heures diurnes, ce qui correspond naturellement au pic de production photovoltaique. Nous adaptons les installations aux rythmes d'exploitation des sites pour maximiser l'autoconsommation et limiter l'energie soutiree au reseau.`,
          `Les acteurs de ${sectorList} n'ont pas les memes contraintes, mais partagent un objectif commun: mieux maitriser les charges. A ${seed.name}, nous separons clairement les usages critiques, les charges decalables et les postes pilotables pour construire une strategie energetique progressive. Cette approche facilite les arbitrages entre retour sur investissement, resilience du site et confort operationnel des equipes internes. Elle ouvre aussi la voie a un pilotage plus fin des consommations en phase avec les cycles d'activite locaux.`,
        ],
      },
      {
        heading: `Methodologie Electrotech QualiPV RGE sur le terrain`,
        paragraphs: [
          `Notre intervention a ${seed.name} suit un cadre rigoureux: diagnostic electrique, verification de la charpente, scenario de production, simulation d'economies et preconisations de pilotage. Electrotech est certifie QualiPV RGE, ce qui garantit un niveau d'exigence eleve a chaque etape, de l'etude initiale a la mise en service. Nous privilegions des composants reconnus pour leur fiabilite et leur tenue dans le temps.`,
          `Sur les chantiers situes pres de ${zoneA} ou de ${zoneB}, nous anticipons les contraintes d'acces, de securite et de planning pour limiter l'impact sur l'activite. Le dossier technique integre schema unifilaire, protection, etiquetage, consignes d'exploitation et plan de controle post-installation. A ${seed.name}, cette organisation permet d'obtenir une installation propre, documentee et facilement maintenable par la suite.`,
        ],
      },
      {
        heading: `Rentabilite solaire et aides mobilisables a ${seed.name}`,
        paragraphs: [
          `L'equilibre economique d'un projet photovoltaique repose sur plusieurs leviers: profil de charge, niveau d'autoconsommation, puissance installee et strategie de valorisation du surplus. A ${seed.name}, nous construisons des hypotheses transparentes et prudentes pour eviter les promesses irrealistes. Le client visualise clairement la trajectoire des economies, le temps de retour et les sensibilites aux evolutions tarifaires.`,
          `Nous accompagnons egalement le montage administratif et l'identification des dispositifs d'aide compatibles avec la situation du site. Cette assistance est decisive pour fiabiliser le budget global et raccourcir les delais de concretisation. Dans ${seed.department}, les projets bien prepares beneficient d'une mise en oeuvre plus fluide, avec une meilleure coordination entre installateur, gestionnaire de reseau et acteurs institutionnels.`,
        ],
      },
      {
        heading: `Maintenance, suivi et optimisation continue`,
        paragraphs: [
          `Une installation performante est une installation suivie. A ${seed.name}, nous mettons en place un pilotage clair: supervision de production, alertes sur derive, lecture des indicateurs de performance et verification periodique des organes de protection. Cette vigilance permet d'identifier rapidement les baisses de rendement liees a l'encrassement, aux ombrages nouveaux ou a une anomalie electrique progressive.`,
          `Le plan de maintenance est adapté à l'environnement professionnel de ${seed.name}, qu'il s'agisse d'un entrepôt logistique, d'un atelier industriel ou d'un bâtiment tertiaire proche de ${zoneC}. Notre objectif reste constant : maintenir un niveau de production stable dans la durée. Des bilans semestriels permettent d'ajuster le pilotage des consommations et de sécuriser le retour sur investissement.`,
        ],
      },
      {
        heading: `Choisir un partenaire local pour votre projet a ${seed.name}`,
        paragraphs: [
          `Le solaire n'est pas un produit standard: c'est un projet territorial qui doit refleter les usages, les contraintes et les ambitions de chaque site. En intervenant regulierement autour de ${seed.name}, nous avons construit une connaissance fine des contextes locaux, des rythmes de consommation et des enjeux de raccordement. Cette proximite permet d'accelerer les decisions et d'eviter les erreurs de conception couteuses.`,
          `Electrotech s'engage sur une relation de long terme: conseil initial, installation, verification des resultats et accompagnement dans l'evolution des besoins. Que le projet concerne l'habitat, un commerce, un atelier ou une exploitation agricole, notre equipe QualiPV RGE construit une feuille de route realiste et mesurable. A ${seed.name}, cette methode transforme l'ensoleillement disponible en performance energetique durable.`,
        ],
      },
    ],
    neighborLinks: seed.neighbors,
    relatedBlogSlug: seed.relatedBlogSlug,
  };
}

const CITY_SEEDS: CitySeed[] = [
  {
    slug: "roquevaire",
    name: "Roquevaire",
    code: "13360",
    department: "Bouches-du-Rhone",
    sunshine: "environ 2 800 heures de soleil par an",
    geography: "la vallee de l'Huveaune entre reliefs et quartiers pavillonnaires",
    zones: ["ZI de la Plaine de Jouques", "Parc d'activites de Napollon", "ZA de la Garenne"],
    sectors: ["artisanat du batiment", "PME industrielles", "commerce de proximite", "services techniques"],
    neighbors: [
      { slug: "aubagne", name: "Aubagne" },
      { slug: "allauch", name: "Allauch" },
      { slug: "plan-de-cuques", name: "Plan-de-Cuques" },
    ],
    relatedBlogSlug: "autoconsommation-entreprise-paca",
  },
  {
    slug: "chateauneuf-les-martigues",
    name: "Chateauneuf-les-Martigues",
    code: "13220",
    department: "Bouches-du-Rhone",
    sunshine: "pres de 2 850 heures de soleil annuelles",
    geography: "un territoire entre l'Etang de Berre et les collines littorales",
    zones: ["Zone d'activites de la Valampe", "ZI de la Mede", "Parc d'activites des Florides"],
    sectors: ["logistique", "chimie-energie", "maintenance industrielle", "services portuaires"],
    neighbors: [
      { slug: "martigues", name: "Martigues" },
      { slug: "gignac-la-nerthe", name: "Gignac-la-Nerthe" },
      { slug: "berre-l-etang", name: "Berre-l'Etang" },
    ],
    relatedBlogSlug: "solaire-zone-industrielle",
  },
  {
    slug: "berre-l-etang",
    name: "Berre-l'Etang",
    code: "13130",
    department: "Bouches-du-Rhone",
    sunshine: "autour de 2 850 heures de soleil chaque annee",
    geography: "la rive orientale de l'Etang de Berre et ses grands sites d'activite",
    zones: ["ZI de Berre", "Plateforme de La Mede", "Parc d'activites des Florides"],
    sectors: ["petrochimie", "logistique", "industrie de process", "services B2B"],
    neighbors: [
      { slug: "vitrolles", name: "Vitrolles" },
      { slug: "rognac", name: "Rognac" },
      { slug: "chateauneuf-les-martigues", name: "Chateauneuf-les-Martigues" },
    ],
    relatedBlogSlug: "photovoltaique-site-industriel",
  },
  {
    slug: "port-de-bouc",
    name: "Port-de-Bouc",
    code: "13110",
    department: "Bouches-du-Rhone",
    sunshine: "environ 2 850 heures de soleil par an",
    geography: "une facade maritime ouverte sur le golfe de Fos",
    zones: ["Zone industrialo-portuaire de Port-de-Bouc", "Plateforme de Caronte", "ZIP de Fos"],
    sectors: ["activites portuaires", "metallurgie", "logistique maritime", "maintenance navale"],
    neighbors: [
      { slug: "fos-sur-mer", name: "Fos-sur-Mer" },
      { slug: "martigues", name: "Martigues" },
      { slug: "istres", name: "Istres" },
    ],
    relatedBlogSlug: "solaire-industrie-portuaire",
  },
  {
    slug: "gignac-la-nerthe",
    name: "Gignac-la-Nerthe",
    code: "13180",
    department: "Bouches-du-Rhone",
    sunshine: "pres de 2 850 heures de soleil annuelles",
    geography: "des coteaux dominant l'etang avec un habitat diffus",
    zones: ["Parc d'activites de la Valampe", "ZA de la Nerthe", "Parc des Aiguilles"],
    sectors: ["artisanat", "transport", "services techniques", "commerce local"],
    neighbors: [
      { slug: "chateauneuf-les-martigues", name: "Chateauneuf-les-Martigues" },
      { slug: "pennes-mirabeau", name: "Les Pennes-Mirabeau" },
      { slug: "vitrolles", name: "Vitrolles" },
    ],
    relatedBlogSlug: "panneaux-solaires-maison-provence",
  },
  {
    slug: "bouc-bel-air",
    name: "Bouc-Bel-Air",
    code: "13320",
    department: "Bouches-du-Rhone",
    sunshine: "environ 2 800 heures de soleil par an",
    geography: "un plateau entre Aix, Gardanne et Marseille",
    zones: ["Pole d'activites de Plan de Campagne", "ZI de la Malle", "Parc d'activites de la Duranne"],
    sectors: ["commerce", "services aux entreprises", "BTP", "activites tertiaires"],
    neighbors: [
      { slug: "gardanne", name: "Gardanne" },
      { slug: "aix-en-provence", name: "Aix-en-Provence" },
      { slug: "pennes-mirabeau", name: "Les Pennes-Mirabeau" },
    ],
    relatedBlogSlug: "dimensionner-installation-photovoltaique",
  },
  {
    slug: "peynier",
    name: "Peynier",
    code: "13790",
    department: "Bouches-du-Rhone",
    sunshine: "autour de 2 800 heures de soleil annuelles",
    geography: "le piemonte de la Sainte-Victoire avec reliefs boises",
    zones: ["Rousset Parc Club", "Zone d'activites de Peynier-Rousset", "ZA de la Treille"],
    sectors: ["microelectronique", "PME innovantes", "sous-traitance industrielle", "logistique legere"],
    neighbors: [
      { slug: "trets", name: "Trets" },
      { slug: "gardanne", name: "Gardanne" },
      { slug: "aix-en-provence", name: "Aix-en-Provence" },
    ],
    relatedBlogSlug: "solaire-pme-industrielle",
  },
  {
    slug: "peyrolles-en-provence",
    name: "Peyrolles-en-Provence",
    code: "13860",
    department: "Bouches-du-Rhone",
    sunshine: "pres de 2 800 heures de soleil par an",
    geography: "la vallee de la Durance au nord du pays d'Aix",
    zones: ["ZA de Peyrolles", "Parc d'activites du Verger", "Zone d'activites de Meyrargues"],
    sectors: ["agroalimentaire", "artisanat local", "services", "activites logistiques"],
    neighbors: [
      { slug: "pertuis", name: "Pertuis" },
      { slug: "aix-en-provence", name: "Aix-en-Provence" },
      { slug: "lambesc", name: "Lambesc" },
    ],
    relatedBlogSlug: "autoconsommation-agricole-provence",
  },
  {
    slug: "saint-cannat",
    name: "Saint-Cannat",
    code: "13760",
    department: "Bouches-du-Rhone",
    sunshine: "environ 2 800 heures de soleil annuelles",
    geography: "la plaine agricole entre Coudoux, Lambesc et Aix",
    zones: ["ZA de la Pile", "Parc d'activites de Lambesc", "ZA de Coudoux"],
    sectors: ["agriculture", "artisanat", "commerce", "services de proximite"],
    neighbors: [
      { slug: "lambesc", name: "Lambesc" },
      { slug: "aix-en-provence", name: "Aix-en-Provence" },
      { slug: "salon-de-provence", name: "Salon-de-Provence" },
    ],
    relatedBlogSlug: "toiture-solaire-maison-individuelle",
  },
  {
    slug: "rognac",
    name: "Rognac",
    code: "13340",
    department: "Bouches-du-Rhone",
    sunshine: "pres de 2 850 heures de soleil par an",
    geography: "entre Etang de Berre, zones de transit et coteaux",
    zones: ["ZI des Cadesteaux", "Zone d'activites de l'Ecopole", "Parc d'activites de Vitropole"],
    sectors: ["transport", "logistique", "industrie legere", "services techniques"],
    neighbors: [
      { slug: "berre-l-etang", name: "Berre-l'Etang" },
      { slug: "vitrolles", name: "Vitrolles" },
      { slug: "lancon-provence", name: "Lançon-Provence" },
    ],
    relatedBlogSlug: "reduction-facture-entreprise",
  },
  {
    slug: "lancon-provence",
    name: "Lancon-Provence",
    code: "13680",
    department: "Bouches-du-Rhone",
    sunshine: "autour de 2 850 heures d'ensoleillement annuel",
    geography: "les plateaux entre Salon et l'Etang de Berre",
    zones: ["Parc d'activites des Sardenas", "ZA de la Garenne", "Parc d'activites de la Crau"],
    sectors: ["logistique", "agroalimentaire", "artisanat", "commerce B2B"],
    neighbors: [
      { slug: "salon-de-provence", name: "Salon-de-Provence" },
      { slug: "rognac", name: "Rognac" },
      { slug: "velaux", name: "Velaux" },
    ],
    relatedBlogSlug: "solaire-entrepot-logistique",
  },
  {
    slug: "velaux",
    name: "Velaux",
    code: "13880",
    department: "Bouches-du-Rhone",
    sunshine: "pres de 2 850 heures de soleil annuelles",
    geography: "des collines ventees entre l'Arc et l'Etang de Berre",
    zones: ["ZA de Velaux", "Vitropole Entreprendre", "Parc de la Verdiere"],
    sectors: ["artisanat", "services", "commerce local", "petite industrie"],
    neighbors: [
      { slug: "vitrolles", name: "Vitrolles" },
      { slug: "lancon-provence", name: "Lançon-Provence" },
      { slug: "aix-en-provence", name: "Aix-en-Provence" },
    ],
    relatedBlogSlug: "solaire-residentiel-provence",
  },
  {
    slug: "pennes-mirabeau",
    name: "Les Pennes-Mirabeau",
    code: "13170",
    department: "Bouches-du-Rhone",
    sunshine: "environ 2 850 heures de soleil par an",
    geography: "un chapelet de quartiers entre Marseille et Vitrolles",
    zones: ["Plan de Campagne", "Parc d'activites de l'Anjoly", "ZI des Estroublans"],
    sectors: ["grande distribution", "logistique", "services", "artisanat"],
    neighbors: [
      { slug: "marseille", name: "Marseille" },
      { slug: "vitrolles", name: "Vitrolles" },
      { slug: "bouc-bel-air", name: "Bouc-Bel-Air" },
    ],
    relatedBlogSlug: "solaire-commerce-et-enseigne",
  },
  {
    slug: "plan-de-cuques",
    name: "Plan-de-Cuques",
    code: "13380",
    department: "Bouches-du-Rhone",
    sunshine: "autour de 2 800 heures de soleil annuelles",
    geography: "les premiers reliefs de l'Etoile au nord-est marseillais",
    zones: ["ZA de Fonterie", "Parc d'activites de Chateau-Gombert", "ZA des Paluds d'Aubagne"],
    sectors: ["commerce", "services", "artisanat", "professions liberales"],
    neighbors: [
      { slug: "allauch", name: "Allauch" },
      { slug: "marseille", name: "Marseille" },
      { slug: "roquevaire", name: "Roquevaire" },
    ],
    relatedBlogSlug: "autoconsommation-villa-paca",
  },
  {
    slug: "allauch",
    name: "Allauch",
    code: "13190",
    department: "Bouches-du-Rhone",
    sunshine: "environ 2 800 heures de soleil chaque annee",
    geography: "des collines calcaires dominant le bassin marseillais",
    zones: ["ZA de Fontvieille", "Parc d'activites de Chateau-Gombert", "ZA des Paluds"],
    sectors: ["services", "artisanat", "BTP", "commerce de proximite"],
    neighbors: [
      { slug: "plan-de-cuques", name: "Plan-de-Cuques" },
      { slug: "marseille", name: "Marseille" },
      { slug: "aubagne", name: "Aubagne" },
    ],
    relatedBlogSlug: "toiture-solaire-zone-urbaine",
  },
  {
    slug: "cassis",
    name: "Cassis",
    code: "13260",
    department: "Bouches-du-Rhone",
    sunshine: "pres de 2 800 heures de soleil annuelles",
    geography: "le littoral des calanques entre falaises et front de mer",
    zones: ["Zone d'activites de Cassis", "ZA des Paluds d'Aubagne", "Parc d'activites de La Ciotat"],
    sectors: ["tourisme", "hotellerie-restauration", "commerce", "services nautiques"],
    neighbors: [
      { slug: "la-ciotat", name: "La Ciotat" },
      { slug: "aubagne", name: "Aubagne" },
      { slug: "roquevaire", name: "Roquevaire" },
    ],
    relatedBlogSlug: "solaire-hotels-restaurants",
  },
  {
    slug: "trets",
    name: "Trets",
    code: "13530",
    department: "Bouches-du-Rhone",
    sunshine: "autour de 2 800 heures de soleil annuelles",
    geography: "la vallee de l'Arc au pied de la Sainte-Victoire",
    zones: ["ZA de la Burliere", "Rousset Parc Club", "ZA de la Gardi"],
    sectors: ["agroalimentaire", "artisanat", "industrie legere", "services"],
    neighbors: [
      { slug: "peynier", name: "Peynier" },
      { slug: "aix-en-provence", name: "Aix-en-Provence" },
      { slug: "gardanne", name: "Gardanne" },
    ],
    relatedBlogSlug: "solaire-territoire-rural",
  },
  {
    slug: "lambesc",
    name: "Lambesc",
    code: "13410",
    department: "Bouches-du-Rhone",
    sunshine: "environ 2 800 heures d'ensoleillement annuel",
    geography: "la transition entre pays d'Aix, Coteaux et plaine agricole",
    zones: ["ZA de Berthoire", "Parc d'activites de Lambesc", "ZA de Saint-Cannat"],
    sectors: ["agriculture", "artisanat", "commerce", "services a la personne"],
    neighbors: [
      { slug: "saint-cannat", name: "Saint-Cannat" },
      { slug: "salon-de-provence", name: "Salon-de-Provence" },
      { slug: "aix-en-provence", name: "Aix-en-Provence" },
    ],
    relatedBlogSlug: "photovoltaique-exploitation-agricole",
  },
  {
    slug: "cavaillon",
    name: "Cavaillon",
    code: "84300",
    department: "Vaucluse",
    sunshine: "environ 2 700 heures de soleil par an",
    geography: "la plaine de la Durance entre Luberon et Alpilles",
    zones: ["MIN de Cavaillon", "ZA des Banquets", "Parc d'activites de Cheval-Blanc"],
    sectors: ["agroalimentaire", "logistique du froid", "commerce de gros", "transport"],
    neighbors: [
      { slug: "l-isle-sur-la-sorgue", name: "L'Isle-sur-la-Sorgue" },
      { slug: "pernes-les-fontaines", name: "Pernes-les-Fontaines" },
      { slug: "cheval-blanc", name: "Cheval-Blanc" },
    ],
    relatedBlogSlug: "solaire-froid-industriel",
  },
  {
    slug: "sorgues",
    name: "Sorgues",
    code: "84700",
    department: "Vaucluse",
    sunshine: "pres de 2 700 heures d'ensoleillement annuel",
    geography: "la plaine rhodanienne au nord d'Avignon",
    zones: ["ZI de Sorgues", "Agroparc Avignon", "Parc d'activites de Vedene"],
    sectors: ["logistique", "agroalimentaire", "distribution", "services industriels"],
    neighbors: [
      { slug: "vedene", name: "Vedene" },
      { slug: "le-pontet", name: "Le Pontet" },
      { slug: "avignon", name: "Avignon" },
    ],
    relatedBlogSlug: "autoconsommation-entrepot",
  },
  {
    slug: "vedene",
    name: "Vedene",
    code: "84270",
    department: "Vaucluse",
    sunshine: "environ 2 700 heures de soleil annuelles",
    geography: "la couronne periurbaine d'Avignon entre plaine et axes routiers",
    zones: ["Parc d'activites de Vedene", "Avignon Nord", "Agroparc"],
    sectors: ["commerce", "logistique", "services", "activites tertiaires"],
    neighbors: [
      { slug: "sorgues", name: "Sorgues" },
      { slug: "le-pontet", name: "Le Pontet" },
      { slug: "avignon", name: "Avignon" },
    ],
    relatedBlogSlug: "solaire-batiment-commercial",
  },
  {
    slug: "le-pontet",
    name: "Le Pontet",
    code: "84130",
    department: "Vaucluse",
    sunshine: "pres de 2 700 heures de soleil par an",
    geography: "un territoire urbain dense en entree nord d'Avignon",
    zones: ["ZA de Fontvert", "Avignon Nord", "Agroparc"],
    sectors: ["grande distribution", "services", "logistique", "commerce specialise"],
    neighbors: [
      { slug: "avignon", name: "Avignon" },
      { slug: "sorgues", name: "Sorgues" },
      { slug: "vedene", name: "Vedene" },
    ],
    relatedBlogSlug: "optimiser-autoconsommation-professionnelle",
  },
  {
    slug: "monteux",
    name: "Monteux",
    code: "84170",
    department: "Vaucluse",
    sunshine: "environ 2 700 heures de soleil annuelles",
    geography: "la plaine du Comtat entre Sorgue et Ouvèze",
    zones: ["ZI de Beaulieu", "Parc d'activites de Monteux", "Zone de Sarrians"],
    sectors: ["agroalimentaire", "emballage", "logistique", "artisanat"],
    neighbors: [
      { slug: "carpentras", name: "Carpentras" },
      { slug: "pernes-les-fontaines", name: "Pernes-les-Fontaines" },
      { slug: "courthezon", name: "Courthezon" },
    ],
    relatedBlogSlug: "solaire-atelier-production",
  },
  {
    slug: "courthezon",
    name: "Courthezon",
    code: "84350",
    department: "Vaucluse",
    sunshine: "pres de 2 700 heures de soleil annuelles",
    geography: "les plaines viticoles entre Orange et Chateauneuf-du-Pape",
    zones: ["ZA de la Barrade", "Parc d'activites de Jonquieres", "Zone d'activites d'Orange Sud"],
    sectors: ["viticulture", "agroalimentaire", "logistique", "artisanat"],
    neighbors: [
      { slug: "orange", name: "Orange" },
      { slug: "sorgues", name: "Sorgues" },
      { slug: "carpentras", name: "Carpentras" },
    ],
    relatedBlogSlug: "solaire-domaine-viticole",
  },
  {
    slug: "pernes-les-fontaines",
    name: "Pernes-les-Fontaines",
    code: "84210",
    department: "Vaucluse",
    sunshine: "autour de 2 700 heures de soleil annuelles",
    geography: "le coeur du Comtat Venaissin entre canaux et terres agricoles",
    zones: ["ZA de Prato", "Parc d'activites de Monteux", "ZA de Saint-Didier"],
    sectors: ["agriculture", "artisanat", "tourisme", "commerce local"],
    neighbors: [
      { slug: "carpentras", name: "Carpentras" },
      { slug: "l-isle-sur-la-sorgue", name: "L'Isle-sur-la-Sorgue" },
      { slug: "cavaillon", name: "Cavaillon" },
    ],
    relatedBlogSlug: "solaire-maison-ancienne-provence",
  },
  {
    slug: "l-isle-sur-la-sorgue",
    name: "L'Isle-sur-la-Sorgue",
    code: "84800",
    department: "Vaucluse",
    sunshine: "pres de 2 700 heures d'ensoleillement annuel",
    geography: "une ville d'eau alimentee par les bras de la Sorgue",
    zones: ["ZA de l'Isle", "Parc d'activites de Cavaillon", "ZA de Fontaine-de-Vaucluse"],
    sectors: ["antiquites", "tourisme", "commerce", "artisanat"],
    neighbors: [
      { slug: "cavaillon", name: "Cavaillon" },
      { slug: "pernes-les-fontaines", name: "Pernes-les-Fontaines" },
      { slug: "apt", name: "Apt" },
    ],
    relatedBlogSlug: "solaire-commerce-centre-ville",
  },
  {
    slug: "bollene",
    name: "Bollene",
    code: "84500",
    department: "Vaucluse",
    sunshine: "environ 2 650 heures de soleil annuelles",
    geography: "la porte nord du Vaucluse entre Rhone et Tricastin",
    zones: ["Zone du Tricastin", "Parc d'activites de Bollene", "ZA de Lapalud"],
    sectors: ["industrie energetique", "logistique", "maintenance", "services techniques"],
    neighbors: [
      { slug: "orange", name: "Orange" },
      { slug: "valreas", name: "Valreas" },
      { slug: "vaison-la-romaine", name: "Vaison-la-Romaine" },
    ],
    relatedBlogSlug: "photovoltaique-site-technique",
  },
  {
    slug: "valreas",
    name: "Valreas",
    code: "84600",
    department: "Vaucluse",
    sunshine: "autour de 2 650 heures de soleil annuelles",
    geography: "l'Enclave des Papes entre collines et plaines agricoles",
    zones: ["ZA de Valreas", "Parc d'activites de Grillon", "ZA de Visan"],
    sectors: ["agroalimentaire", "cartonnage", "artisanat", "commerce"],
    neighbors: [
      { slug: "bollene", name: "Bollene" },
      { slug: "vaison-la-romaine", name: "Vaison-la-Romaine" },
      { slug: "orange", name: "Orange" },
    ],
    relatedBlogSlug: "solaire-territoire-rural-vaucluse",
  },
  {
    slug: "vaison-la-romaine",
    name: "Vaison-la-Romaine",
    code: "84110",
    department: "Vaucluse",
    sunshine: "pres de 2 650 heures de soleil annuelles",
    geography: "la vallee de l'Ouveze au pied des Dentelles",
    zones: ["ZA de l'Ouveze", "Parc d'activites de Vaison", "ZA de Nyonsais"],
    sectors: ["tourisme", "viticulture", "commerce", "services"],
    neighbors: [
      { slug: "valreas", name: "Valreas" },
      { slug: "orange", name: "Orange" },
      { slug: "carpentras", name: "Carpentras" },
    ],
    relatedBlogSlug: "solaire-tourisme-hebergement",
  },
  {
    slug: "gordes",
    name: "Gordes",
    code: "84220",
    department: "Vaucluse",
    sunshine: "environ 2 700 heures de soleil par an",
    geography: "les hauteurs du Luberon et les hameaux de pierre",
    zones: ["ZA des Imberts", "Parc d'activites de Coustellet", "ZA de Cabrieres-d'Avignon"],
    sectors: ["tourisme haut de gamme", "artisanat d'art", "commerce", "hebergement"],
    neighbors: [
      { slug: "l-isle-sur-la-sorgue", name: "L'Isle-sur-la-Sorgue" },
      { slug: "cavaillon", name: "Cavaillon" },
      { slug: "apt", name: "Apt" },
    ],
    relatedBlogSlug: "integration-solaire-batiment-patrimonial",
  },
  {
    slug: "cheval-blanc",
    name: "Cheval-Blanc",
    code: "84460",
    department: "Vaucluse",
    sunshine: "pres de 2 700 heures de soleil annuelles",
    geography: "la plaine de la Durance au pied du Luberon",
    zones: ["Parc d'activites de Cheval-Blanc", "MIN de Cavaillon", "ZA de Taillades"],
    sectors: ["agriculture", "logistique agro", "artisanat", "commerce local"],
    neighbors: [
      { slug: "cavaillon", name: "Cavaillon" },
      { slug: "l-isle-sur-la-sorgue", name: "L'Isle-sur-la-Sorgue" },
      { slug: "apt", name: "Apt" },
    ],
    relatedBlogSlug: "solaire-agriculture-irrigation",
  },
  {
    slug: "cadenet",
    name: "Cadenet",
    code: "84160",
    department: "Vaucluse",
    sunshine: "environ 2 700 heures de soleil annuelles",
    geography: "la rive sud de la Durance face au Luberon",
    zones: ["ZA de Cadenet", "Parc d'activites de Pertuis", "ZA de Villelaure"],
    sectors: ["agriculture", "artisanat", "commerce", "services"],
    neighbors: [
      { slug: "pertuis", name: "Pertuis" },
      { slug: "lourmarin", name: "Lourmarin" },
      { slug: "apt", name: "Apt" },
    ],
    relatedBlogSlug: "projet-solaire-autoconsommation-rurale",
  },
  {
    slug: "lourmarin",
    name: "Lourmarin",
    code: "84160",
    department: "Vaucluse",
    sunshine: "pres de 2 700 heures de soleil annuelles",
    geography: "la combe sud du Luberon entre villages et domaines",
    zones: ["ZA de Cadenet", "Parc d'activites de Pertuis", "ZA de Cucuron"],
    sectors: ["tourisme", "hebergement", "artisanat", "commerce local"],
    neighbors: [
      { slug: "cadenet", name: "Cadenet" },
      { slug: "pertuis", name: "Pertuis" },
      { slug: "apt", name: "Apt" },
    ],
    relatedBlogSlug: "solaire-maison-dhotes-provence",
  },
  {
    slug: "frejus",
    name: "Frejus",
    code: "83600",
    department: "Var",
    sunshine: "environ 2 800 heures de soleil annuelles",
    geography: "un vaste territoire littoral entre massif de l'Esterel et Argens",
    zones: ["Zone du Capitou", "Parc d'activites de la Palud", "Base nature Francois Leotard"],
    sectors: ["tourisme", "commerce", "BTP", "services urbains"],
    neighbors: [
      { slug: "saint-raphael", name: "Saint-Raphael" },
      { slug: "draguignan", name: "Draguignan" },
      { slug: "hyeres", name: "Hyeres" },
    ],
    relatedBlogSlug: "solaire-littoral-mediteraneen",
  },
  {
    slug: "la-seyne-sur-mer",
    name: "La Seyne-sur-Mer",
    code: "83500",
    department: "Var",
    sunshine: "pres de 2 900 heures de soleil par an",
    geography: "la rade de Toulon et un tissu urbain maritime dense",
    zones: ["Parc de Brgaillon", "Zone des Playes", "Technopole de la Mer"],
    sectors: ["construction navale", "logistique portuaire", "services maritimes", "commerce"],
    neighbors: [
      { slug: "toulon", name: "Toulon" },
      { slug: "six-fours-les-plages", name: "Six-Fours-les-Plages" },
      { slug: "ollioules", name: "Ollioules" },
    ],
    relatedBlogSlug: "photovoltaique-secteur-maritime",
  },
  {
    slug: "draguignan",
    name: "Draguignan",
    code: "83300",
    department: "Var",
    sunshine: "autour de 2 800 heures de soleil annuelles",
    geography: "l'arriere-pays varois entre plaines et collines",
    zones: ["Parc d'activites Saint-Hermentaire", "ZA des Incapis", "Parc d'activites des Nouradons"],
    sectors: ["administration", "services", "artisanat", "logistique locale"],
    neighbors: [
      { slug: "frejus", name: "Frejus" },
      { slug: "saint-raphael", name: "Saint-Raphael" },
      { slug: "brignoles", name: "Brignoles" },
    ],
    relatedBlogSlug: "solaire-batiment-public",
  },
  {
    slug: "hyeres",
    name: "Hyeres",
    code: "83400",
    department: "Var",
    sunshine: "pres de 2 900 heures de soleil annuelles",
    geography: "la bande littorale et les plaines horticoles de l'est toulonnais",
    zones: ["Zone du Palyvestre", "Parc d'activites du Roubaud", "Port de Hyeres"],
    sectors: ["horticulture", "tourisme", "aeronautique legere", "services"],
    neighbors: [
      { slug: "la-garde", name: "La Garde" },
      { slug: "toulon", name: "Toulon" },
      { slug: "la-seyne-sur-mer", name: "La Seyne-sur-Mer" },
    ],
    relatedBlogSlug: "solaire-exploitation-horticole",
  },
  {
    slug: "saint-raphael",
    name: "Saint-Raphael",
    code: "83700",
    department: "Var",
    sunshine: "environ 2 800 heures de soleil par an",
    geography: "le front littoral de l'Esterel et les quartiers residentiels",
    zones: ["ZA du Cerceron", "Parc d'activites de Boulouris", "Zone du Capitou Frejus"],
    sectors: ["tourisme", "services", "commerce", "construction"],
    neighbors: [
      { slug: "frejus", name: "Frejus" },
      { slug: "draguignan", name: "Draguignan" },
      { slug: "hyeres", name: "Hyeres" },
    ],
    relatedBlogSlug: "solaire-residence-secondaire",
  },
  {
    slug: "ollioules",
    name: "Ollioules",
    code: "83190",
    department: "Var",
    sunshine: "pres de 2 900 heures de soleil annuelles",
    geography: "la vallee de la Reppe aux portes ouest de Toulon",
    zones: ["Technopole de la Mer", "Zone des Playes", "Parc d'activites Camp Laurent"],
    sectors: ["innovation maritime", "services", "commerce", "artisanat"],
    neighbors: [
      { slug: "la-seyne-sur-mer", name: "La Seyne-sur-Mer" },
      { slug: "six-fours-les-plages", name: "Six-Fours-les-Plages" },
      { slug: "toulon", name: "Toulon" },
    ],
    relatedBlogSlug: "solaire-pole-innovation",
  },
  {
    slug: "la-garde",
    name: "La Garde",
    code: "83130",
    department: "Var",
    sunshine: "environ 2 900 heures de soleil annuelles",
    geography: "la plaine littorale est de la metropole toulonnaise",
    zones: ["Parc d'activites de Toulon-Est", "Zone de La Pauline", "Parc de Sainte-Musse"],
    sectors: ["commerce", "logistique", "enseignement-superieur", "services"],
    neighbors: [
      { slug: "hyeres", name: "Hyeres" },
      { slug: "toulon", name: "Toulon" },
      { slug: "la-seyne-sur-mer", name: "La Seyne-sur-Mer" },
    ],
    relatedBlogSlug: "solaire-campus-et-tertiaire",
  },
  {
    slug: "six-fours-les-plages",
    name: "Six-Fours-les-Plages",
    code: "83140",
    department: "Var",
    sunshine: "pres de 2 900 heures de soleil annuelles",
    geography: "la facade ouest de la rade avec secteurs residentiels et zones d'activite",
    zones: ["Zone des Playes", "Parc de la Millonne", "Port du Brusc"],
    sectors: ["tourisme", "commerce", "services maritimes", "artisanat"],
    neighbors: [
      { slug: "la-seyne-sur-mer", name: "La Seyne-sur-Mer" },
      { slug: "ollioules", name: "Ollioules" },
      { slug: "toulon", name: "Toulon" },
    ],
    relatedBlogSlug: "solaire-littoral-residentiel",
  },
  {
    slug: "antibes",
    name: "Antibes",
    code: "06600",
    department: "Alpes-Maritimes",
    sunshine: "autour de 2 700 heures de soleil annuelles",
    geography: "le littoral azureen entre cap d'Antibes et Sophia Antipolis",
    zones: ["Sophia Antipolis", "Zone des Trois Moulins", "Port Vauban"],
    sectors: ["numerique", "tourisme", "services", "nautisme"],
    neighbors: [
      { slug: "cannes", name: "Cannes" },
      { slug: "grasse", name: "Grasse" },
      { slug: "nice", name: "Nice" },
    ],
    relatedBlogSlug: "solaire-tertiaire-cote-dazur",
  },
  {
    slug: "cannes",
    name: "Cannes",
    code: "06400",
    department: "Alpes-Maritimes",
    sunshine: "pres de 2 700 heures de soleil annuelles",
    geography: "une ville littorale dense entre baie et collines",
    zones: ["Bastide Rouge", "Parc d'activites de la Frayere", "Port Canto"],
    sectors: ["evenementiel", "tourisme", "hotellerie", "services premium"],
    neighbors: [
      { slug: "antibes", name: "Antibes" },
      { slug: "grasse", name: "Grasse" },
      { slug: "nice", name: "Nice" },
    ],
    relatedBlogSlug: "solaire-hotellerie-cote-dazur",
  },
  {
    slug: "grasse",
    name: "Grasse",
    code: "06130",
    department: "Alpes-Maritimes",
    sunshine: "environ 2 700 heures de soleil annuelles",
    geography: "les collines prealpines entre vallons et bassins d'emploi",
    zones: ["Parc d'activites de Grasse", "ZA des Bois de Grasse", "Sophia Antipolis"],
    sectors: ["parfumerie", "chimie fine", "logistique", "services"],
    neighbors: [
      { slug: "cannes", name: "Cannes" },
      { slug: "antibes", name: "Antibes" },
      { slug: "menton", name: "Menton" },
    ],
    relatedBlogSlug: "solaire-industrie-chimie-fine",
  },
  {
    slug: "menton",
    name: "Menton",
    code: "06500",
    department: "Alpes-Maritimes",
    sunshine: "pres de 2 700 heures de soleil annuelles",
    geography: "la Riviera franco-italienne entre mer et reliefs abrupts",
    zones: ["ZA du Carei", "Port de Garavan", "Parc d'activites de Roquebrune"],
    sectors: ["tourisme", "services", "commerce", "horticulture"],
    neighbors: [
      { slug: "nice", name: "Nice" },
      { slug: "antibes", name: "Antibes" },
      { slug: "cannes", name: "Cannes" },
    ],
    relatedBlogSlug: "solaire-zone-littorale-contraintes",
  },
  {
    slug: "digne-les-bains",
    name: "Digne-les-Bains",
    code: "04000",
    department: "Alpes-de-Haute-Provence",
    sunshine: "environ 2 500 heures de soleil par an",
    geography: "la vallee de la Bléone en moyenne montagne",
    zones: ["Parc Saint-Christophe", "ZA des Ferréols", "Parc d'activites de Gaubert"],
    sectors: ["services publics", "sante", "artisanat", "tourisme thermal"],
    neighbors: [
      { slug: "manosque", name: "Manosque" },
      { slug: "forcalquier", name: "Forcalquier" },
      { slug: "sisteron", name: "Sisteron" },
    ],
    relatedBlogSlug: "solaire-moyenne-montagne",
  },
  {
    slug: "sisteron",
    name: "Sisteron",
    code: "04200",
    department: "Alpes-de-Haute-Provence",
    sunshine: "pres de 2 500 heures d'ensoleillement annuel",
    geography: "la cluse de la Durance entre Alpes et Provence",
    zones: ["Val de Durance", "Parc d'activites Sisteron", "ZA de Peipin"],
    sectors: ["logistique", "agroalimentaire", "services", "commerce"],
    neighbors: [
      { slug: "digne-les-bains", name: "Digne-les-Bains" },
      { slug: "forcalquier", name: "Forcalquier" },
      { slug: "manosque", name: "Manosque" },
    ],
    relatedBlogSlug: "solaire-couloir-durance",
  },
  {
    slug: "forcalquier",
    name: "Forcalquier",
    code: "04300",
    department: "Alpes-de-Haute-Provence",
    sunshine: "autour de 2 600 heures de soleil annuelles",
    geography: "les collines du Luberon alpin et les plateaux ouverts",
    zones: ["Parc d'activites de Forcalquier", "Zone de Mane", "Parc d'activites de Volx"],
    sectors: ["agroalimentaire", "cosmetique naturelle", "tourisme", "artisanat"],
    neighbors: [
      { slug: "volx", name: "Volx" },
      { slug: "manosque", name: "Manosque" },
      { slug: "digne-les-bains", name: "Digne-les-Bains" },
    ],
    relatedBlogSlug: "solaire-pme-rurale",
  },
  {
    slug: "volx",
    name: "Volx",
    code: "04130",
    department: "Alpes-de-Haute-Provence",
    sunshine: "pres de 2 600 heures de soleil annuelles",
    geography: "la vallee de la Durance au sud de Manosque",
    zones: ["Parc d'activites de Volx", "Zone Saint-Joseph", "Parc d'activites de Manosque Sud"],
    sectors: ["industrie legere", "artisanat", "services", "logistique locale"],
    neighbors: [
      { slug: "forcalquier", name: "Forcalquier" },
      { slug: "manosque", name: "Manosque" },
      { slug: "digne-les-bains", name: "Digne-les-Bains" },
    ],
    relatedBlogSlug: "autoconsommation-site-mixte",
  },
  {
    slug: "gap",
    name: "Gap",
    code: "05000",
    department: "Hautes-Alpes",
    sunshine: "environ 2 400 heures de soleil annuelles",
    geography: "un bassin alpin ouvert entre montagnes et zones d'activite",
    zones: ["Micropolis", "Tokoro", "ZA de Gap Sud"],
    sectors: ["services", "commerce", "logistique", "BTP"],
    neighbors: [
      { slug: "embrun", name: "Embrun" },
      { slug: "veynes", name: "Veynes" },
      { slug: "briancon", name: "Briancon" },
    ],
    relatedBlogSlug: "solaire-territoire-alpin",
  },
  {
    slug: "briancon",
    name: "Briancon",
    code: "05100",
    department: "Hautes-Alpes",
    sunshine: "pres de 2 500 heures de soleil annuelles",
    geography: "la haute montagne autour de la vallee de la Durance superieure",
    zones: ["ZA Sud Briancon", "Parc d'activites de Chantemerle", "Zone de l'Argentiere"],
    sectors: ["tourisme de montagne", "services", "commerce", "construction"],
    neighbors: [
      { slug: "gap", name: "Gap" },
      { slug: "embrun", name: "Embrun" },
      { slug: "veynes", name: "Veynes" },
    ],
    relatedBlogSlug: "solaire-altitude-et-neige",
  },
  {
    slug: "embrun",
    name: "Embrun",
    code: "05200",
    department: "Hautes-Alpes",
    sunshine: "autour de 2 500 heures de soleil annuelles",
    geography: "le bassin du lac de Serre-Poncon entre montagnes et vallees",
    zones: ["ZA d'Embrun", "Parc d'activites de Baratier", "Zone de Chorges"],
    sectors: ["tourisme", "services", "commerce", "artisanat"],
    neighbors: [
      { slug: "gap", name: "Gap" },
      { slug: "briancon", name: "Briancon" },
      { slug: "veynes", name: "Veynes" },
    ],
    relatedBlogSlug: "solaire-lac-serre-poncon",
  },
  {
    slug: "laragne-monteglin",
    name: "Laragne-Monteglin",
    code: "05300",
    department: "Hautes-Alpes",
    sunshine: "environ 2 500 heures de soleil annuelles",
    geography: "la porte sud des Hautes-Alpes entre Buech et Durance",
    zones: ["ZA du Plan d'Eau", "Parc d'activites du Buech", "Zone de Sisteron Nord"],
    sectors: ["agroalimentaire", "artisanat", "logistique", "services"],
    neighbors: [
      { slug: "gap", name: "Gap" },
      { slug: "veynes", name: "Veynes" },
      { slug: "embrun", name: "Embrun" },
    ],
    relatedBlogSlug: "solaire-petite-industrie-alpine",
  },
  {
    slug: "veynes",
    name: "Veynes",
    code: "05400",
    department: "Hautes-Alpes",
    sunshine: "pres de 2 400 heures de soleil annuelles",
    geography: "la vallee du Buech et les plateaux du Gapençais",
    zones: ["ZA de Veynes", "Parc d'activites des Iscles", "ZA de Gap Sud"],
    sectors: ["services", "artisanat", "commerce", "activites ferroviaires"],
    neighbors: [
      { slug: "gap", name: "Gap" },
      { slug: "laragne-monteglin", name: "Laragne-Monteglin" },
      { slug: "embrun", name: "Embrun" },
    ],
    relatedBlogSlug: "solaire-vallee-alpine",
  },
];

const VALID_BLOG_SLUGS = [
  "panneaux-solaires-entreprises-paca-2025",
  "autoconsommation-solaire-reduire-facture-electricite",
  "installation-photovoltaique-marseille-professionnels",
  "ombrieres-photovoltaiques-parking-entreprise",
  "aides-subventions-panneaux-solaires-entreprises-2025",
  "centrale-photovoltaique-industrielle-guide",
  "panneaux-solaires-aix-en-provence",
  "installation-solaire-avignon-vaucluse",
  "batteries-stockage-solaire-entreprises-2025",
  "maintenance-panneaux-solaires-entreprise",
  "revente-electricite-solaire-tarifs-edf-oa-2025",
  "agrivoltaisme-paca-agriculture-solaire",
  "qualipv-rge-installateur-certifie-2025",
  "panneaux-solaires-collectivites-batiments-publics-paca",
  "transition-energetique-pme-solaire-2025",
  "installation-solaire-toulon-var",
  "panneaux-solaires-entrepots-logistiques-industrie",
  "prix-panneaux-solaires-professionnels-2025",
  "loi-aper-obligation-solaire-parkings-entreprises",
  "solaire-photovoltaique-valorisation-immobilier-professionnel",
];

export const CITY_PAGES_REMAINING: Record<string, CityPageContent> =
  Object.fromEntries(
    CITY_SEEDS.map((seed, index) => {
      const page = buildContent(seed);
      page.relatedBlogSlug =
        VALID_BLOG_SLUGS[index % VALID_BLOG_SLUGS.length];
      return [seed.slug, page];
    })
  );
